[pytest]
testpaths = tests
pythonpath = .
base_url = https://dev.bmb.az
markers =
    smoke: smoke tests
    regression: regression tests

    p0: Critical priority
    p1: High priority
    p2: Medium priority
    p3: Low priority
    p4: Trivial priority